  [1m[35m (899.7ms)[0m  [1m[35mCREATE DATABASE "music_app_development" ENCODING = 'unicode'[0m
  â†³ bin/rails:9
  [1m[35m (302.3ms)[0m  [1m[35mCREATE DATABASE "music_app_test" ENCODING = 'unicode'[0m
  â†³ bin/rails:9
  [1m[35m (145.9ms)[0m  [1m[35mCREATE TABLE "schema_migrations" ("version" character varying NOT NULL PRIMARY KEY)[0m
  â†³ bin/rails:9
  [1m[35m (4.0ms)[0m  [1m[35mCREATE TABLE "ar_internal_metadata" ("key" character varying NOT NULL PRIMARY KEY, "value" character varying, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)[0m
  â†³ bin/rails:9
  [1m[35m (1.4ms)[0m  [1m[34mSELECT pg_try_advisory_lock(4505726345591715405)[0m
  â†³ bin/rails:9
  [1m[35m (2.0ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  â†³ bin/rails:9
Migrating to CreateUsers (20210406150245)
  [1m[35m (0.4ms)[0m  [1m[34mSELECT pg_advisory_unlock(4505726345591715405)[0m
  â†³ bin/rails:9
  [1m[35m (0.4ms)[0m  [1m[34mSELECT pg_try_advisory_lock(4505726345591715405)[0m
  â†³ bin/rails:9
  [1m[35m (1.1ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  â†³ bin/rails:9
Migrating to CreateUsers (20210406150245)
  [1m[35m (23.1ms)[0m  [1m[35mBEGIN[0m
  â†³ bin/rails:9
  [1m[35m (52.9ms)[0m  [1m[35mCREATE TABLE "users" ("id" bigserial primary key, "email" character varying NOT NULL, "password_digest" character varying NOT NULL, "session_token" character varying NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)[0m
  â†³ db/migrate/20210406150245_create_users.rb:3
  [1m[35m (29.9ms)[0m  [1m[35mCREATE UNIQUE INDEX  "index_users_on_session_token" ON "users"  ("session_token")[0m
  â†³ db/migrate/20210406150245_create_users.rb:10
  [1m[35m (9.6ms)[0m  [1m[35mCREATE UNIQUE INDEX  "index_users_on_email" ON "users"  ("email")[0m
  â†³ db/migrate/20210406150245_create_users.rb:11
  [1m[36mActiveRecord::SchemaMigration Create (27.7ms)[0m  [1m[32mINSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"[0m  [["version", "20210406150245"]]
  â†³ bin/rails:9
  [1m[35m (2.2ms)[0m  [1m[35mCOMMIT[0m
  â†³ bin/rails:9
  [1m[36mActiveRecord::InternalMetadata Load (2.8ms)[0m  [1m[34mSELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2[0m  [["key", "environment"], ["LIMIT", 1]]
  â†³ bin/rails:9
  [1m[35m (0.3ms)[0m  [1m[35mBEGIN[0m
  â†³ bin/rails:9
  [1m[36mActiveRecord::InternalMetadata Create (1.5ms)[0m  [1m[32mINSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "key"[0m  [["key", "environment"], ["value", "development"], ["created_at", "2021-04-06 15:09:40.487480"], ["updated_at", "2021-04-06 15:09:40.487480"]]
  â†³ bin/rails:9
  [1m[35m (0.4ms)[0m  [1m[35mCOMMIT[0m
  â†³ bin/rails:9
  [1m[35m (0.3ms)[0m  [1m[34mSELECT pg_advisory_unlock(4505726345591715405)[0m
  â†³ bin/rails:9
  [1m[35m (0.4ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  â†³ bin/rails:9
  [1m[35m (0.3ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  â†³ bin/rails:9
Started GET "/new_user" for ::1 at 2021-04-06 14:05:36 -0400
  [1m[35m (1.1ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  â†³ /Users/t51putt/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.5/lib/active_record/log_subscriber.rb:98
  
ActionController::RoutingError (No route matches [GET] "/new_user"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/users" for ::1 at 2021-04-06 14:05:50 -0400
  
ActionController::RoutingError (No route matches [GET] "/users"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/users" for ::1 at 2021-04-06 14:06:36 -0400
  
ActionController::RoutingError (No route matches [GET] "/users"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/user" for ::1 at 2021-04-06 14:06:57 -0400
  
ActionController::RoutingError (No route matches [GET] "/user"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/" for ::1 at 2021-04-06 14:07:03 -0400
Processing by Rails::WelcomeController#index as HTML
  Rendering /Users/t51putt/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.5/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /Users/t51putt/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.5/lib/rails/templates/rails/welcome/index.html.erb (5.8ms)
Completed 200 OK in 32ms (Views: 12.3ms | ActiveRecord: 0.0ms)


Started GET "/" for ::1 at 2021-04-06 14:07:17 -0400
Processing by Rails::WelcomeController#index as HTML
  Rendering /Users/t51putt/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.5/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /Users/t51putt/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.5/lib/rails/templates/rails/welcome/index.html.erb (3.8ms)
Completed 200 OK in 31ms (Views: 21.4ms | ActiveRecord: 0.0ms)


Started GET "/users" for ::1 at 2021-04-06 14:11:31 -0400
  
ActionController::RoutingError (No route matches [GET] "/users"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/new_user" for ::1 at 2021-04-06 14:11:46 -0400
  
ActionController::RoutingError (No route matches [GET] "/new_user"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/user" for ::1 at 2021-04-06 14:13:23 -0400
  
ActionController::RoutingError (No route matches [GET] "/user"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/user" for ::1 at 2021-04-06 14:13:49 -0400
  
ActionController::RoutingError (No route matches [GET] "/user"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/new_session" for ::1 at 2021-04-06 14:15:30 -0400
  
ActionController::RoutingError (No route matches [GET] "/new_session"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/users" for ::1 at 2021-04-06 14:17:34 -0400
  
ActionController::RoutingError (No route matches [GET] "/users"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/users" for ::1 at 2021-04-06 14:17:43 -0400
  
ActionController::RoutingError (No route matches [GET] "/users"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/new_session" for ::1 at 2021-04-06 14:21:17 -0400
  
ActionController::RoutingError (No route matches [GET] "/new_session"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/users" for ::1 at 2021-04-06 14:21:24 -0400
  
ActionController::RoutingError (No route matches [GET] "/users"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/users_path" for ::1 at 2021-04-06 14:24:11 -0400
  
ActionController::RoutingError (No route matches [GET] "/users_path"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/users" for ::1 at 2021-04-06 14:32:56 -0400
  
ActionController::RoutingError (No route matches [GET] "/users"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/users" for ::1 at 2021-04-06 14:37:59 -0400
  
ActionController::RoutingError (No route matches [GET] "/users"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/users" for ::1 at 2021-04-06 14:38:03 -0400
  
ActionController::RoutingError (No route matches [GET] "/users"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/users" for ::1 at 2021-04-06 14:39:27 -0400
  
ActionController::RoutingError (No route matches [GET] "/users"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/sessions" for ::1 at 2021-04-06 14:40:11 -0400
  
ActionController::RoutingError (No route matches [GET] "/sessions"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/sessions" for ::1 at 2021-04-06 14:40:16 -0400
  
ActionController::RoutingError (No route matches [GET] "/sessions"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/session" for ::1 at 2021-04-06 14:40:19 -0400
  
ActionController::RoutingError (No route matches [GET] "/session"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/new_session" for ::1 at 2021-04-06 14:40:45 -0400
  
ActionController::RoutingError (No route matches [GET] "/new_session"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/users" for ::1 at 2021-04-06 14:44:06 -0400
  
ActionController::RoutingError (No route matches [GET] "/users"):
  
actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.5) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/users/new" for ::1 at 2021-04-06 14:44:08 -0400

TypeError - superclass must be a Class (Module given):
  app/controllers/users_controller.rb:1:in `<top (required)>'

Started POST "/__better_errors/2df815fd23d7a4c6/variables" for ::1 at 2021-04-06 14:44:09 -0400
Started GET "/users/new" for ::1 at 2021-04-06 14:44:51 -0400

SyntaxError - syntax error, unexpected keyword_end, expecting ')'
    end
    ^~~:
  app/controllers/application_controller.rb:21:in `'
  app/controllers/users_controller.rb:1:in `<top (required)>'

Started POST "/__better_errors/6e74c914a58bd148/variables" for ::1 at 2021-04-06 14:44:51 -0400
Started GET "/users/new" for ::1 at 2021-04-06 14:45:49 -0400
Processing by UsersController#new as HTML
  Rendering users/new.html.erb within layouts/application
  Rendered users/new.html.erb within layouts/application (6.4ms)
Completed 500 Internal Server Error in 122ms (ActiveRecord: 91.8ms)



ActionController::UrlGenerationError - No route matches {:action=>"show", :controller=>"users"}, missing required keys: [:id]:
  app/views/users/new.html.erb:12:in `_app_views_users_new_html_erb__2403583730565181683_70203166063360'
  app/controllers/users_controller.rb:16:in `new'

Started POST "/__better_errors/e19f95cfbc63bd76/variables" for ::1 at 2021-04-06 14:45:49 -0400
Started GET "/users/new" for ::1 at 2021-04-06 14:46:27 -0400
Processing by UsersController#new as HTML
  Rendering users/new.html.erb within layouts/application
  Rendered users/new.html.erb within layouts/application (2.3ms)
Completed 200 OK in 534ms (Views: 532.6ms | ActiveRecord: 0.0ms)


Started GET "/users/new" for ::1 at 2021-04-06 14:47:08 -0400
Processing by UsersController#new as HTML
  Rendering users/new.html.erb within layouts/application
  Rendered users/new.html.erb within layouts/application (0.9ms)
Completed 200 OK in 86ms (Views: 82.9ms | ActiveRecord: 0.0ms)


Started POST "/users" for ::1 at 2021-04-06 14:47:14 -0400
Processing by UsersController#create as HTML
  Parameters: {"user"=>{"email"=>"", "password"=>"[FILTERED]"}}
Can't verify CSRF token authenticity.
Completed 422 Unprocessable Entity in 2ms (ActiveRecord: 0.0ms)



ActionController::InvalidAuthenticityToken - ActionController::InvalidAuthenticityToken:

Started POST "/__better_errors/e41ecd98f8ea0aba/variables" for ::1 at 2021-04-06 14:47:14 -0400
Started GET "/users/new" for ::1 at 2021-04-06 14:57:47 -0400
Processing by UsersController#new as HTML
  Rendering users/new.html.erb within layouts/application
  Rendered users/new.html.erb within layouts/application (1.0ms)
Completed 200 OK in 101ms (Views: 99.5ms | ActiveRecord: 0.0ms)


Started POST "/users" for ::1 at 2021-04-06 14:58:09 -0400
Processing by UsersController#create as HTML
  Parameters: {"user"=>{"email"=>"travis", "password"=>"[FILTERED]"}}
Can't verify CSRF token authenticity.
Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms)



ActionController::InvalidAuthenticityToken - ActionController::InvalidAuthenticityToken:

Started POST "/__better_errors/79dcc6a6b62a906d/variables" for ::1 at 2021-04-06 14:58:10 -0400
